MySFDCProject/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitor1__c</fullName>
        <label>Competitor1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor2__c</fullName>
        <label>Competitor2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor3__c</fullName>
        <label>Competitor3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor_1_Price__c</fullName>
        <label>Competitor 1 Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_2_Price__c</fullName>
        <label>Competitor 2 Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_3_Price__c</fullName>
        <label>Competitor 3 Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Leading_Caompetitor__c</fullName>
        <label>Leading Caompetitor</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MySFDCProject/src/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {
    //To update lead competitor with lowest price
    public static void leadCompetitorUpdate(List<Opportunity> opps){
        for(Opportunity opp:opps){
          List<Decimal> competitorPrices=new List<Decimal>();
           competitorPrices.add(opp.Competitor_1_Price__c) ;
            competitorPrices.add(opp.Competitor_2_Price__c) ;
            competitorPrices.add(opp.Competitor_3_Price__c) ;
            
            List<String> competitors=new List<String>();
            competitors.add(opp.Competitor1__c);
            competitors.add(opp.Competitor2__c);
            competitors.add(opp.Competitor3__c);
            Decimal lowestPrice;
            Integer lowesPricePosition;
            for(Integer i=0; i<competitorPrices.size(); i++ ){
                Decimal currentPrice=competitorPrices.get(i);
                if(lowestPrice==null||currentPrice>lowestPrice){
                    lowestPrice=currentPrice;
                    lowesPricePosition=i;
                    
                }
                
            }
            
opp.Leading_Caompetitor__c=competitors.get(lowesPricePosition);
            
        }
        
    }
}